### ISSUE TITLE
.java文件之间的依赖关系

### ISSUE THREAD

**Issue by Nickname-1725** [qiuxianglian/regex#1]
您的仓库文件看起来比较多，但是依赖关系不是很清晰，请问能否考虑对仓库文档进行更新

**Comment by qiuxianglian** [comment]
用ieda打开后，设置模块源码位置为当前目录，可以用其跳转功能查看源码关系

**Comment by qiuxianglian** [comment]
![选区_086](https://github.com/qiuxianglian/regex/assets/143075119/4089d942-c176-43a5-8118-6bff0e44c6dc)
@Nickname-1725
